apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: test-pod-02
  name: test-pod-02
spec:
  containers:
  - image: nginx
    name: test-pod-02
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
