apiVersion: vmoperator.vmware.com/v1alpha1
kind: VirtualMachine
metadata:
  name: centos-vm
  namespace: ns01
spec:
  networkInterfaces:
  - networkName: "tanzu-vlan-41-workload"
    networkType: vsphere-distributed
  className: best-effort-xsmall
  imageName: ob-20611104-ubuntu-2004-amd64-vmi-k8s-v1.23.8---vmware.2-tkg.1-zshippable
  powerState: poweredOn
  storageClass: k8s-policy
  vmMetadata:
    configMapName: centos-vm-cfm
    transport: OvfEnv
