apiVersion: vmoperator.vmware.com/v1alpha1
kind: VirtualMachine
metadata:
  name: centos-vm
  namespace: ns01
spec:
  networkInterfaces:
  - networkName: "workload"
    networkType: vsphere-distributed
  className: best-effort-xsmall
  imageName: centos01
  powerState: poweredOn
  storageClass: k8s-policy
  vmMetadata:
    configMapName: centos-vm-cfm
    transport: OvfEnv
