apiVersion: run.tanzu.vmware.com/v1alpha2
kind: TanzuKubernetesCluster
metadata:
  name: cluster03
  namespace: ns01
spec:
  topology:
    controlPlane:
      replicas: 1
      vmClass: best-effort-small
      storageClass: k8s-policy
      tkr:  
        reference:
          name: v1.22.9---vmware.1-tkg.1.cc71bc8
    nodePools:
    - name: worker
      replicas: 1
      vmClass: best-effort-small
      storageClass: k8s-policy
      tkr:  
        reference:
          name: v1.22.9---vmware.1-tkg.1.cc71bc8
